services:
  back:
    build: ./new_back
    ports:
      - "8000:8000"
    volumes:
      # Путь к статике
      - ./new_back/static:/static:z
    environment:
      - mode=prod
    networks:
      - turbo
  front:
    build: ./front/kali_front
    ports:
      - "5173:5173"
    networks:
      - turbo
networks:
  turbo:
